### ISSUE TITLE
Inference code 

### ISSUE THREAD

**Issue by shihabrashid-ucr** [carriex/recomp#7]
Hi, thank you for the great work and for releasing the model cards! I was wondering is there any simple inference code with your model?
From what I understand, in order to run the abstraction compressor with custom sets of documents for one query, I need to run the `train_hf_summarization_model.py` with the input file formatted like the one you provided. Is it possible to provide a simple function that will take `k` documents, the query and just output the abstractive summary given your trained model?
If it is not possible to provide it, any guides to writing such function will be incredibly helpful!

**Comment by carriex** [comment]
Hi there, the code [here](https://github.com/carriex/recomp?tab=readme-ov-file#abstractive-compressor) provided is for inference.
