### ISSUE TITLE
Oracle Dataset

### ISSUE THREAD

**Issue by JungDongwon** [carriex/recomp#8]
Hi, thank you for the great work!

Can you share the oracle extractive and abstractive compressions you used for the experiment? Would appreciate it! 
Thanks!

**Comment by carriex** [comment]
Hi there! I have uploaded the prompts for oracle compressions for FLAN-UL2 for NQ, TQA, HotpotQA in the respective directory [here](https://drive.google.com/drive/folders/1ZYukUsVunXWJukvZfjb3nKcJZ5BY0Bv8?usp=sharing).

**Comment by JungDongwon** [comment]
Thanks so much!
